nop:
  stage: build
  script:
    - echo nothing to see here

pages:
  stage: deploy
  script:
    - mkdir public
    - mv *.html public/
    - mv *.css public/
  artifacts:
    paths:
      - public
  only:
    - main
